name: SonarQube

on:
  workflow_dispatch:

jobs:
  scan:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      - uses: skitsanosinc/sonarqube-qualitygate-generate-report@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: sonar.retraced.com:9000
          SONAR_PROJECT: default-dashboard