name: SonarQube

on:
  workflow_dispatch:

  #push:
  #branches:
  #  - master # or the name of your main branch
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: |
          sudo apt install -y jq

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Collect issues
        if: always()
        run: |
          curl "http://${{ secrets.SONAR_TOKEN }}:@sonar.retraced.com:9000/api/issues/search?componentKeys=web-analytics-service&resolved=no" | jq '.issues[] | {key, message, severity, component, textRange, repo: "${{github.repository}}", pr: "${{github.event.number}}" }' >report.json
          curl -H "Content-Type: application/json" --data @report.json "https://webhook.site/7aff8ce3-bdaa-413b-9fce-3a47f613860d"
